language: ruby
env:
  global:
    - ORG=konveyor
    - REPO=move2kube                
    # HOMEBREW_BINTRAY_USER
    # HOMEBREW_BINTRAY_KEY

cache:
  directories:
    - "$HOME/.cache/pip"
    - "$HOME/.gem/ruby"
    - "$HOME/Library/Caches/Homebrew"
    - "$HOME/.cache/Homebrew"   
    
install:
  - git config --global --unset protocol.version
  - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  - brew tap davidchall/test-bot

script:
  - brew test-bot --root-url=https://dl.bintray.com/$ORG/bottles-$REPO --verbose

jobs:
  include:
    - &run-osx
      os: osx
      osx_image: xcode12.2
      env: OS=catalina-10.15.7

    - <<: *run-osx
      os: osx
      osx_image: xcode11.3
      env: OS=mojave-10.14.6

    - <<: *run-osx
      os: osx
      osx_image: xcode10.1
      env: OS=high_sierra-10.13

before_cache:
  - brew cleanup -s
  - brew cask cleanup
  - rm -f ~/Library/Caches/Homebrew/linkage.db ~/.cache/Homebrew/linkage.db
  - brew list
  - du -h ~/Library/Caches/Homebrew || du -h ~/.cache/Homebrew/linkage.db
